### ISSUE TITLE
cdk destroy error

### ISSUE THREAD

**Issue by piedpiper-ff4084** [aws-samples/aws-dev-hour-backend#11]
When I executed the `cdk destroy` command I encountered this error:

 ❌  AwsdevhourStack: destroy failed Error: The stack named AwsdevhourStack is in a failed state. You may need to delete it from the AWS console : DELETE_FAILED (The following resource(s) failed to delete: [cdkreknimgagebucketABE44D40]. )
    at Object.waitForStackDelete (/Users/FranciscoFranco/.nvm/versions/node/v12.6.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:277:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at Object.destroyStack (/Users/FranciscoFranco/.nvm/versions/node/v12.6.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:379:28)
    at CdkToolkit.destroy (/Users/FranciscoFranco/.nvm/versions/node/v12.6.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:252:9)
    at initCommandLine (/Users/FranciscoFranco/.nvm/versions/node/v12.6.0/lib/node_modules/aws-cdk/bin/cdk.ts:204:9)
The stack named AwsdevhourStack is in a failed state. You may need to delete it from the AWS console : DELETE_FAILED (The following resource(s) failed to delete: [cdkreknimgagebucketABE44D40]. )

**Comment by piedpiper-ff4084** [comment]
Sorry I forgot to execute this command first `aws s3 rm --recursive s3://{imageBucket}`.
Issue resolved.
