### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by jedrekdomanski** [aws-samples/aws-dev-hour-backend#9]
Hi, everytime I run any command it gives me this error:
`cdk synth -v`
```
ENOENT: no such file or directory, stat '/Users/jedrek/workspace/devhr-project/rekognitionlambda'
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:122:23)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```
I have copy-pasted all the code from your repo to my local app.
`cdk bootstrap aws://.../eu-central-1 -v`
```
ENOENT: no such file or directory, stat '/Users/jedrek/workspace/devhr-project/rekognitionlambda'
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:122:23)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```
Why am I getting this error? Any idea?

**Comment by jedrekdomanski** [comment]
@newtondigital Your code here differs from the code in the video. Could you please update it?

**Comment by IAM-DBro** [comment]
Did npm install work correctly for you?

**Comment by jedrekdomanski** [comment]
Yes, it did.

**Comment by jedrekdomanski** [comment]
I'm wondering if they defined the file that I am missing themselves? Anyway, I will try cloning the code and see if it works.
